### ISSUE TITLE
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-staging.records WHERE content LIKE '%4.4.4.4%'' at line 1

### ISSUE THREAD

**Issue by lukasmedia** [Napsty/scripts#12]
I want to replace "4.4.4.4" with "5.5.5.5":

I test & execute on our test/staging server first:

./pdns-search-replace.sh -s 4.4.4.4 -r 5.5.5.5 -u root -d myapp-staging -n

the result:

ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-staging.records WHERE content LIKE '%4.4.4.4%'' at line 1

**Comment by Napsty** [comment]
Thanks for reporting the issue @lukasmedia 
Please try it with this version: 
https://raw.githubusercontent.com/Napsty/scripts/issue-12/pdns/pdns-search-replace.sh

Please confirm whether it works or not. Thx.

**Comment by lukasmedia** [comment]
Great; working fine now!
