### ISSUE TITLE
osx

### ISSUE THREAD

**Issue by BananaAcid** [Napsty/scripts#3]
./compact_couchdb.sh -H service.abc.de -S -u Admin -p pwabc -d

Json read error: line 2 column 0: '[' or '{' expected near end of file
Found 0 databases

**Comment by Napsty** [comment]
Thanks for reporting a problem.
Please give some additional details. OS? CouchDB version? Bash version?

**Comment by BananaAcid** [comment]
OSX: 10.13.6
Native shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
CouchDB: 2.3.1

**Comment by Napsty** [comment]
Hi @BananaAcid 
Can you please try the newest version? DL link:
https://raw.githubusercontent.com/Napsty/scripts/issue-3/couchdb/compact_couchdb.sh
It's not merged to master branch yet.

The new version contains additional checks to identify http errors which might be at the source of the error you got. 

I successfully tested it with a "current" Bash version (`GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)`) and also with an older eol Bash Version (`GNU bash, version 3.1.17(1)-release (i586-suse-linux)`).

Off topic: How can Apple ship such an old Bash version in a recent OS? :-1:
