### ISSUE TITLE
Using a password on the command line interface can be insecure

### ISSUE THREAD

**Issue by oldfart101** [Napsty/scripts#6]
mysql error
Using a password on the command line interface can be insecure

**Comment by creed205** [comment]
I also am having the same error and then it doesn't do anything. Will be looking at that error specifically to see if it can be bypassed as I assume this is a mysql issue.

**Comment by Napsty** [comment]
On which script do you get this?

**Comment by creed205** [comment]
> On which script do you get this?

this is with zoneminder-event-cleanup.sh

**Comment by creed205** [comment]
I tried to pass on the password using another method which doesn't return an error but I don't get any feedback from the script. It doesn't say it's deleting anything and ends after some time (couple of minutes). 
Method used: MYSQL_PWD=xxxxxxxx mysql -u root -e "statement"

**Comment by Brawn1** [comment]
i have changed the script to work with zoneminder 1.24+, and added feature to use Mysql Docker and normal Mysql connection.

**Comment by Napsty** [comment]
fixed in https://github.com/Napsty/scripts/commit/c3f0237b1dfd7428e1adb19f2fadbb8bb048516e
